server:
  port: 8080
spring:
  application:
    name: empc-java
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude:
    -  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: <your-url>
      database: tododb
      authentication-database: admin