#server:
#  port: 8080
#spring:
#  application:
#    name: empc-java
#  jpa:
#    hibernate:
#      ddl-auto: update
#  autoconfigure:
#    exclude:
#    -  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  data:
#    mongodb:
#      uri: mongodb+srv://jiocoders:Jiocoders2024@cluster-jiocoders.pvobg1n.mongodb.net/tododb?retryWrites=true&w=majority&appName=Cluster-Jiocoders
##      uri: mongodb+srv://use-your-mongodb-url&appName=Cluster0
#      database: tododb
##      authentication-database: admin